### PR TITLE
Adds multi repository support

### PR DESCRIPTION
**Pull request by spencergibb**

### CODE REVIEW

**Comment by spencergibb** [comment]
Any references to `slug` (ie `org/repo`) could use some review and suggestions.

**Comment by wilkinsona** [comment]
Thanks for the PR. The changes are rather more invasive than I thought they would need to be. I started to sketch out an alternative approach to see if that thought was reasonable. It's still work in progress as the issue closing notification from `StandardFeedbackListener` doesn't happen right now but it's been quite fruitful: https://github.com/wilkinsona/issue-bot/commit/bfb3cec7a18566e12cc9ffb2ea3f4d7ab857bdc1. I suspect it doesn't quite do everything that's proposed here just yet either, but I think it should be fairly easy to build on top of it. What do you think?

**Comment by spencergibb** [comment]
Looks good to me. Should I restart on top of your change or wait until it is merged?

**Comment by spencergibb** [comment]
If you didn't want to add complexity to the feedback and triage properties (ie different properties for different orgs or repos), we could certainly run our own. That's all that would be missing for me I think. 

On second thought, we'll likely need separate github credentials too. Maybe for now this is good enough and we run our own?

**Pull request closed without merging**
